[WIP]--Add docs for Pulsar Spark connector 3.1.1 release
streamnative/pulsar-hub pull request #160
Opened 2022-03-16 03:04 UTC by Huanli-Meng

### Motivation
Pulsar Spark connector 3.1.1 is released. Therefore, add docs for this release.

### Modification
- Add a doc for Pulsar Spark connector 3.1.1
- Add two images for Pulsar Spark connector 3.1.1
- Remove broken links in version 2.4.5 as the linked docs are removed from the doc website.
### Preview link

2022-03-21 14:43 UTC, teachwrite requested changes
@Huanli-Meng I just have a few small changes in this document.

2022-03-21 19:04 UTC, nlu90 approved these changes

2022-03-22 02:34 UTC, Huanli-Meng commented
@teachwrite Thanks for your valuable comments. I have updated the doc. Could you please help review it and feel free to approve it if there is no more comment. Thanks.

2022-03-24 14:52 UTC, teachwrite approved these changes
LGTM

2022-03-24 15:00 UTC, merged