Auto sync docs from AWS EventBridge sink connector repo to SN Hub
streamnative/pulsar-hub pull request #211
Opened 2023-05-25 04:10 UTC by shibd

2023-05-25 04:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamnative/pulsar-hub?pullRequest=211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamnative/pulsar-hub?pullRequest=211) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamnative/pulsar-hub?pullRequest=211) it.</sub>

2023-05-25 06:01 UTC, urfreespace commented
<img width="901" alt="image" src="https://github.com/streamnative/pulsar-hub/assets/76024046/1b02ff34-38b4-4ad8-96a4-16a2f3250e29">
@shibd

2023-05-25 06:03 UTC, urfreespace requested changes
<img width="901" alt="image" src="https://github.com/streamnative/pulsar-hub/assets/76024046/1b02ff34-38b4-4ad8-96a4-16a2f3250e29">
@shibd https://github.com/streamnative/pulsar-io-amqp-1-0/tree/master/docs

2023-05-26 05:11 UTC, shibd commented
Re Create by #212

2023-05-26 05:11 UTC, closed without merging