Add kafka sink and source 3.1.0.4 doc
streamnative/pulsar-hub pull request #321
Opened 2023-10-23 09:57 UTC by RobertIndie

2023-10-23 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/streamnative/pulsar-hub?pullRequest=321) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/streamnative/pulsar-hub?pullRequest=321) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/streamnative/pulsar-hub?pullRequest=321) it.</sub>

2023-10-23 10:19 UTC, jak78 requested changes
Fixed some typos - see the comments

2023-10-23 10:19 UTC, jak78 commented on connectors/kafka-source/3.1.0.4/kafka-source.md
> +Depending on the environment, there are several ways to create an Kafka sink connector:
```suggestion
Depending on the environment, there are several ways to create a Kafka source connector:
```

2023-10-23 10:19 UTC, jak78 commented on connectors/kafka-source/3.1.0.4/kafka-source.md
> +No matter how you create an Kafka sink connector, the minimum connector configuration contains the following parameters:
```suggestion
No matter how you create a Kafka source connector, the minimum connector configuration contains the following parameters:
```

2023-10-24 13:44 UTC, shibd approved these changes

2023-10-30 09:43 UTC, jak78 approved these changes

2023-10-30 09:46 UTC, merged